"""
Fetches the current Nifty 500 constituent list from NSE and saves it to stocks.csv
(one symbol per line, no .NS suffix — screener.py appends that itself).

Run this occasionally (e.g. monthly) to keep the universe current, since NSE
index constituents change periodically.

NSE blocks plain requests without browser-like headers, so we first hit the
homepage to pick up cookies, then request the CSV.
"""

import requests
import sys
import io
import pandas as pd

NSE_HOME = "https://www.nseindia.com"
NIFTY500_CSV_URL = "https://archives.nseindia.com/content/indices/ind_nifty500list.csv"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
    ),
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}


def fetch_nifty500_symbols() -> list[str]:
    session = requests.Session()
    session.headers.update(HEADERS)

    # Warm up session to get cookies NSE expects before allowing the CSV request
    session.get(NSE_HOME, timeout=15)

    resp = session.get(NIFTY500_CSV_URL, timeout=15)
    resp.raise_for_status()

    df = pd.read_csv(io.StringIO(resp.text))
    # The CSV has a "Symbol" column
    symbols = df["Symbol"].dropna().astype(str).str.strip().tolist()
    return symbols


def main():
    try:
        symbols = fetch_nifty500_symbols()
        if not symbols:
            raise ValueError("Empty symbol list returned")
    except Exception as e:
        print(f"Failed to fetch Nifty 500 list from NSE: {e}")
        print("You can manually download the CSV from:")
        print("  https://www.niftyindices.com/indices/equity/broad-based-indices/nifty-500")
        print("and save the 'Symbol' column, one per line, into stocks.csv")
        sys.exit(1)

    with open("stocks.csv", "w", encoding="utf-8") as f:
        f.write("# Nifty 500 symbols (NSE, no .NS suffix) — auto-generated by fetch_nifty500.py\n")
        for s in symbols:
            f.write(s + "\n")

    print(f"Saved {len(symbols)} symbols to stocks.csv")


if __name__ == "__main__":
    main()
